version: "3"
   
services:
    frontend:
        image: tapeart/frontend:latest
        container_name: frontend
        ports:
          - 3000:3000
        depends_on: 
          - backend  

    backend:
        image: tapeart/backend:latest
        container_name: backend
        command: uvicorn api:app --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"