####################################################################
# This playbook configures a webserver to run dreambooth
# It exposes dreambooth via an API endpoint
####################################################################

- name: Deploy dreambooth to a server
  hosts: dreambooth_servers
  become: true
  tasks:

    # Install Dependencies
    - name: Update Cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        state: present
        name: ['git', 'python3', 'ssmtp', 'mutt', 'npm', nginx]

    - name: Create conda directory
      file:
        state: directory
        path: conda

    - name: Download conda installer script
      command:
        cmd: wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
        chdir: conda

    - name: Install miniconda
      command: ./conda/Miniconda3-py39_4.12.0-Linux-x86_64.sh

    # Clone github repo for dreambooth
    - name: Clone dreambooth github repo
      command:
        cmd: git clone https://github.com/JoePenna/Dreambooth-Stable-Diffusion
        warn: false

    # Transfer training script
    - name: Transfer training script
      template:
        src: files/beginTraining.sh
        dest: /home/ubuntu/beginTraining.sh

    # Make the script executable
    - name: Make training script executable
      file:
        path: /home/ubuntu/beginTraining.sh
        mode: +x
        owner: ubuntu

    # Configure mailing service
    - name: Add app key environment variable
      ansible.builtin.blockinfile:
        path: "/etc/ssmtp/ssmtp.conf"
        block: |
          UseSTARTTLS=no
          FromLineOverride=YES
          root=username@gmail.com
          mailhub=smtp.gmail.com:465
          AuthUser=username@gmail.com
          AuthPass=xxxxxxxxxxxxx
          rewriteDomain=gmail.com
          FromLineOverride=YES
          UseTLS=YES
    
    - name: Reload 'ssmtp'
      service:
        name: ssmtp
        state: reloaded

    # Transfer node server files
    - name: Transfer node server package.json template
      template:
        src: files/package.json
        dest: /home/ubuntu/node-server/package.json
    
    - name: Transfer node server template
      template:
        src: files/server.js
        dest: /home/ubuntu/node-server/server.js

    # Setup nginx
    - name: Copy nginx reverse-proxy configuration
      template:
        src:  files/nginx.conf
        dest: /etc/nginx/sites-available/noxus.conf

    - name: Unlink default template
      command: unlink /etc/nginx/sites-enabled/default

    - name: Enable NGINX reverse-proxy configuration
      command:
        cmd: ln -s /etc/nginx/sites-available/noxus.conf /etc/nginx/sites-enabled/noxus.conf
        warn: false

    - name: Restart NGINX
      service:
        name: nginx
        state: reloaded

    - name: Make ubuntu owner of all files in it's directory
      command:
        cmd: chown -R ubuntu:ubuntu /home/ubuntu