name: noxus

on:
  # Triggers the workflow on push or pull request events but only for the Dev branch
#   push:
#     branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: pulls code from github repo
        uses: actions/checkout@v2

      - name: setup a node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
#           cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          pwd
          npm ci
          npm run build --if-present
        env:
          CI: false

        
          
  build-backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: pulls code from github repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
