name: testing dockerization

on:
  # # Triggers the workflow on push or pull request events but only for the Dev branch
  # push:
  #   branches: [ dev ]
  #   paths-ignore:
  #     - '**.md'
  # pull_request:
  #   branches: [ dev ]
  #   paths-ignore:
  #     - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Frontend/noxus'

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: pulls code from github repo
        uses: actions/checkout@v2

      - name: setup a node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          pwd
          npm ci
          npm run build --if-present
        env:
          CI: false

        
          
  build-backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: pulls code from github repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  frontend-image:
    needs: build-frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/noxus

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  backend-image:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
